In [7]:
import pandas as pd
from googlesearch import search

In [18]:
# load df from csv
sample_df = pd.read_csv("2023-02-15sample.csv")
sample_df

      ID                       Team_Name
0   2440                Nevada Wolf Pack
1   2856      California Baptist Lancers
2    325         Cleveland State Vikings
3   2352      Loyola Maryland Greyhounds
4     61           Georgia Lady Bulldogs
5   2449        North Dakota State Bison
6   2057                  Belmont Bruins
7   2443          New Orleans Privateers
8    350         UNC Wilmington Seahawks
9    127         Michigan State Spartans
10   151           East Carolina Pirates
11  2193       East Tennessee State Bucs
12    94         Northern Kentucky Norse
13  2571  South Dakota State Jackrabbits
14  2250                Gonzaga Bulldogs
15  2579        South Carolina Gamecocks
16    25         California Golden Bears
17  2771              Merrimack Warriors
18    24               Stanford Cardinal
19  2241   Gardner-Webb Runnin' Bulldogs

In [16]:
twitter_dict = []
instagram_dict = []
sample_df.reset_index()
for index in sample_df.index:
    twitter = "ERROR"
    instagram = "ERROR"
    query = f"{sample_df['Team_Name'][index]} wbb"
    twitter_query = search(query + " twitter", num=3)
    for result in twitter_query:
        if "twitter.com" in result:
            twitter = result[:result.find('?')]
            break
    ig_query = search(query + " instagram", num=3)
    for result in ig_query:
        if "instagram.com" in result:
            result_clean_index = result.find('?')
            if (result_clean_index > 0):
                instagram = result[:result.find('?')]
            else:
                instagram = result
            break
    twitter_dict.append(twitter)
    instagram_dict.append(instagram)
    print(twitter)
    print(instagram)

https://twitter.com/NevadaWBB
https://www.instagram.com/nevadawbb/
https://twitter.com/CBUwbb
https://www.instagram.com/cbuwbb/
https://twitter.com/CSU_WBasketball
https://www.instagram.com/csu_wbasketball/
https://twitter.com/LoyolaWBB
https://www.instagram.com/loyolawbb/
https://twitter.com/UGA_WB
https://www.instagram.com/uga_wbb/
https://twitter.com/NDSUwbb
https://www.instagram.com/ndsuwbb/
https://twitter.com/BelmontWBB
https://www.instagram.com/belmontwbb/
https://twitter.com/PrivateersWBB
https://www.instagram.com/privateerswbb/
https://twitter.com/UNCWwomenshoops
https://www.instagram.com/uncwwomenshoops/
https://twitter.com/MSU_WBasketball
https://www.instagram.com/msu_wbasketball/
https://twitter.com/ECUWBB
https://www.instagram.com/ecuwbb/
https://twitter.com/ETSU_WB
https://www.instagram.com/etsu_wbb/
https://twitter.com/NKUNorseWBB
https://www.instagram.com/nkunorsewbb/
https://twitter.com/GoJacksWBB
https://www.instagram.com/gojackswbb/
https://twitter.com/ZagWBB
https://www.instagram.com/zagwbb/
https://twitter.com/GamecockWBB
https://www.instagram.com/gamecockwbb/
https://twitter.com/CalWBBall
https://www.instagram.com/calwbball/
https://twitter.com/MerrimackWBB
https://www.instagram.com/merrimackwbb/
https://twitter.com/StanfordWBB
https://www.instagram.com/stanfordwbb/
https://twitter.com/GWU_WBK
https://www.instagram.com/gwu_wbk/

In [19]:
socials_df = pd.DataFrame(
    {'Twitter': twitter_dict, 'Instagram': instagram_dict})
sample_df = sample_df.join(
    socials_df)
sample_df

,ID,Team_Name,Twitter,Instagram
0,2440,Nevada Wolf Pack,https://twitter.com/NevadaWBB,https://www.instagram.com/nevadawbb/
1,2856,California Baptist Lancers,https://twitter.com/CBUwbb,https://www.instagram.com/cbuwbb/
2,325,Cleveland State Vikings,https://twitter.com/CSU_WBasketball,https://www.instagram.com/csu_wbasketball/
3,2352,Loyola Maryland Greyhounds,https://twitter.com/LoyolaWBB,https://www.instagram.com/loyolawbb/
4,61,Georgia Lady Bulldogs,https://twitter.com/UGA_WB,https://www.instagram.com/uga_wbb/
5,2449,North Dakota State Bison,https://twitter.com/NDSUwbb,https://www.instagram.com/ndsuwbb/
6,2057,Belmont Bruins,https://twitter.com/BelmontWBB,https://www.instagram.com/belmontwbb/
7,2443,New Orleans Privateers,https://twitter.com/PrivateersWBB,https://www.instagram.com/privateerswbb/
8,350,UNC Wilmington Seahawks,https://twitter.com/UNCWwomenshoops,https://www.instagram.com/uncwwomenshoops/
9,127,Michigan State Spartans,https://twitter.com/MSU_WBasketball,https://www.instagram.com/msu_wbasketball/
10,151,East Carolina Pirates,https://twitter.com/ECUWBB,https://www.instagram.com/ecuwbb/
11,2193,East Tennessee State Bucs,https://twitter.com/ETSU_WB,https://www.instagram.com/etsu_wbb/
12,94,Northern Kentucky Norse,https://twitter.com/NKUNorseWBB,https://www.instagram.com/nkunorsewbb/
13,2571,South Dakota State Jackrabbits,https://twitter.com/GoJacksWBB,https://www.instagram.com/gojackswbb/
14,2250,Gonzaga Bulldogs,https://twitter.com/ZagWBB,https://www.instagram.com/zagwbb/
15,2579,South Carolina Gamecocks,https://twitter.com/GamecockWBB,https://www.instagram.com/gamecockwbb/
16,25,California Golden Bears,https://twitter.com/CalWBBall,https://www.instagram.com/calwbball/
17,2771,Merrimack Warriors,https://twitter.com/MerrimackWBB,https://www.instagram.com/merrimackwbb/
18,24,Stanford Cardinal,https://twitter.com/StanfordWBB,https://www.instagram.com/stanfordwbb/
19,2241,Gardner-Webb Runnin' Bulldogs,https://twitter.com/GWU_WBK,https://www.instagram.com/gwu_wbk/